export const IMAGES = {
  expiringCoursesForwardIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G_da.png"),
  expiringCoursesBackIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G_c.png"),
  announcementsIcon: require("../assets/images/notifications_active_FILL0_wgh.png"),
  inProgressCoursesBackIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G_cn.png"),
  inProgressCoursesForwardIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G_co.png"),
  mandatoryTrainingBackIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G.png"),
  mandatoryTrainingForwardIcon: require("../assets/images/arrow_back_ios_FILL0_wght400_G_bx.png"),
  mandatoryTrainingAlertTop: require("../assets/images/info_FILL0_wght400_GRAD0_opsz2.png"),
  mandatoryTrainingAlertBottom: require("../assets/images/info_FILL0_wght400_GRAD0_opsz2_bv.png"),
  cyberSecurityBadge2: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_@2x.png"),
  cyberSecurityBadge3: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_ba@2x.png"),
  cyberSecurityBadge4: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_bb@2x.png"),
  cyberSecurityBadge5: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_.png"),
  cyberSecurityBadge6: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_ba.png"),
  cyberSecurityBadge7: require("../assets/images/n_023_Cyber_Secuirty_Badge_con_bb.png"),
  cyberSecurityBadge8: require("../assets/images/n_023_Cyber_Secuirty_Badge_con.png"),
  searchIcon: require("../assets/images/search_FILL0_wght400_GRAD0_ops.png"),
  dafImage: require("../assets/images/DAF_003_Clean_Stack_V01_clean-.png"),
  digitalLearningImage: require("../assets/images/DU_blue_logo-01_small.png"),
  jkoImage: require("../assets/images/JKO_black_logo.png"),
  dauImage: require("../assets/images/dau_black.png"),
  dafELearningImage: require("../assets/images/Logo2_small.png"),
  myLearningImage: require("../assets/images/MyLearning_Blue_logo-01.png"),
  myTrainingImage: require("../assets/images/myTrainng_blue_logo-01_small.png"),
  jkoLogo: require("../assets/images/JKO_black_logo_cy.png"),
  profileIcon: require("../assets/images/account_circle_FILL0_wght400_G.png"),
  platformCatalogIcon: require("../assets/images/book_5_FILL0_wght400_GRAD0_ops.png"),
  completedCoursesIcon: require("../assets/images/done_FILL0_wght400_GRAD0_opsz2.png"),
  savedCoursesIcon: require("../assets/images/save_FILL0_wght400_GRAD0_opsz2.png"),
  proficienciesIcon: require("../assets/images/person_FILL0_wght400_GRAD0_ops.png"),
  transcriptsIcon: require("../assets/images/library_books_FILL0_wght400_GR_dj.png"),
  reportsIcon: require("../assets/images/library_books_FILL0_wght400_GR.png"),
  helpDeskIcon: require("../assets/images/support_agent_FILL0_wght400_GR.png"),
};

// export const COMPONENTS = {
//   headerComponent: require("../components/headerSVG.svg"),
// };
