# Generated by Django 5.0 on 2024-01-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='UserCurrentCourses',
        ),
    ]
