# Generated by Django 5.0 on 2024-01-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_react_usercurrentcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentcourses',
            name='user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
