# Generated by Django 5.0 on 2024-01-08 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usercurrentcourses_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_short_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=15)),
                ('course_description', models.CharField(max_length=150)),
                ('course_image_id', models.IntegerField(null=True)),
                ('course_completion_percentage', models.IntegerField(null=True)),
                ('last_attempted_date', models.DateTimeField(null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_short_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=15)),
                ('course_description', models.CharField(max_length=150)),
                ('course_image_id', models.IntegerField(null=True)),
                ('course_completion_percentage', models.IntegerField(null=True)),
                ('last_attempted_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCurrentCourses',
        ),
    ]
