# Generated by Django 5.0 on 2024-01-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0005_appuser_first_name_appuser_last_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='DxpUserProfile',
        ),
    ]
