# Generated by Django 5.0 on 2024-01-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0006_rename_appuser_dxpuserprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DxpUserProfile',
            new_name='AppUser',
        ),
    ]
