# Generated by Django 5.0 on 2024-01-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_dxpuserprofile_appuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentCourses',
            new_name='DXPCourses',
        ),
    ]
