# Generated by Django 5.0 on 2024-01-26 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_currentcourses_dxpcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxpcourses',
            name='course_completion_percentage',
        ),
        migrations.RemoveField(
            model_name='dxpcourses',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='dxpcourses',
            name='course_image_id',
        ),
        migrations.RemoveField(
            model_name='dxpcourses',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='dxpcourses',
            name='course_short_name',
        ),
        migrations.RemoveField(
            model_name='dxpcourses',
            name='last_attempted_date',
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='format',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='id_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='learning_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='new_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='short_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dxpcourses',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dxpcourses',
            name='course_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='ExpiringCourses',
        ),
    ]
