# Generated by Django 5.0 on 2024-01-29 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_dxpcourses_course_completion_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='base',
            field=models.CharField(default='lackland', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='cellular',
            field=models.CharField(default='2134343223', max_length=15),
        ),
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='appuser',
            name='current_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='edipi',
            field=models.CharField(default='asdufyas7df87sdfsdyfsd9fs9d', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='first_access_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_access_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='rank',
            field=models.CharField(default='SGT', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='time_zone',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
