# Generated by Django 5.0 on 2024-01-29 18:11

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_user_id_appuser_id_appuser_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxpcourses',
            name='users',
        ),
        migrations.CreateModel(
            name='DXPCourseCompletions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_id', models.BigIntegerField(blank=True)),
                ('edipi', models.CharField(max_length=100)),
                ('enrolled', models.TimeField(default=app.models.default_start_time)),
                ('started', models.TimeField(default=app.models.default_start_time)),
                ('completed', models.TimeField(default=app.models.default_start_time)),
                ('course_id', models.ManyToManyField(to='app.dxpcourses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
