# Generated by Django 5.0 on 2024-01-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dxpcourseenrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxpcoursecompletions',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='dxpcourseenrollments',
            name='course_id',
        ),
        migrations.AddField(
            model_name='dxpcoursecompletions',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dxpcourses'),
        ),
        migrations.AddField(
            model_name='dxpcourseenrollments',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dxpcourses'),
        ),
    ]
