# Generated by Django 5.0.4 on 2024-05-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_dxpcoursecompletions_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxpcoursecompletions',
            name='course_id',
        ),
        migrations.AddField(
            model_name='dxpcoursecompletions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app.dxpcourses'),
        ),
        migrations.AlterField(
            model_name='dxpcourseenrollments',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.dxpcourses'),
        ),
    ]
